local _, Bam = ...

local locale = GetLocale and GetLocale() or "enUS"

local translations = {
    enUS = {
        SETTINGS_TITLE = "Bam Together",
        SETTINGS_SUBTITLE = "Classic BAM sound for critical hits",
        ENABLED = "Enable Bam Together",
        MELEE_CRITS = "Trigger on melee critical hits",
        SPELL_CRITS = "Trigger on spell critical hits",
        FINISHER = "BAAAM! on a critical finisher/kill",
        MUTE_IN_DUNGEON = "Mute sound and critical-hit chat inside dungeons",
        MUTE_IN_GROUP = "Mute sound and critical-hit chat while in a group",
        PARTY_BAM = "Share BAMs with party members and hear theirs",
        CRIT_CHAT = "Show critical damage in chat",
        CHAT_EXAMPLE = "Example: BAM!  1,284 CRIT  →  Target name",
        THROTTLE = "Sound anti-spam delay: %.2f seconds",
        THROTTLE_HELP = "0 = every detected crit. This slider affects sounds only, not chat messages.",
        TEST = "Test",
        CRIT_SOUND = "Crit sound: %s",
        FINISHER_SOUND = "Finisher sound: %s",
        SHUFFLE = "Shuffle",
        DEBUG = "Diagnostic messages in chat",
        DEBUG_HELP = "Diagnostics show the detected crit type, attack state and discarded duplicate events.",
        DETECTION = "Detection",
        DETECTION_HELP = "Crit detection is approximate: group hits on the same target can also trigger it. Hidden combat data is skipped; damage may be unavailable.",
        CRIT_LABEL = "CRIT",
        FINISHER_LABEL = "FINISHER",
        SPELL_CRIT = "Spell crit detected",
        MELEE_CRIT = "Melee crit detected",
        DUPLICATE = "Duplicate UNIT_COMBAT event discarded",
        PARTY_RECEIVED = "Party BAM received",
        CLAIM_DUPLICATE = "Crit already claimed by a party member, skipped",
        LOADED = "v%s loaded. /bam opens the settings.",
        ENABLED_MSG = "enabled",
        DISABLED_MSG = "disabled",
        RESET_MSG = "Settings reset.",
        SOUND_ERROR = "The sound could not be played. Check the sounds folder.",
    },

    deDE = {
        SETTINGS_TITLE = "Bam Together",
        SETTINGS_SUBTITLE = "Klassischer BAM-Sound für kritische Treffer",
        ENABLED = "Bam Together aktivieren",
        MELEE_CRITS = "Nahkampf-Krits auslösen",
        SPELL_CRITS = "Zauber-Krits auslösen",
        FINISHER = "BAAAM! bei einem kritischen Finisher/Kill",
        MUTE_IN_DUNGEON = "Sound und Krit-Chat in Dungeons stummschalten",
        MUTE_IN_GROUP = "Sound und Krit-Chat in Gruppen stummschalten",
        PARTY_BAM = "BAMs mit Gruppenmitgliedern teilen und ihre hören",
        CRIT_CHAT = "Krit-Schaden im Chat anzeigen",
        CHAT_EXAMPLE = "Beispiel: BAM!  1.284 KRIT  →  Zielname",
        THROTTLE = "Anti-Spam-Abstand für Sounds: %.2f Sekunden",
        THROTTLE_HELP = "0 = jeder erkannte Krit. Der Regler betrifft nur Sounds, nicht die Chatmeldung.",
        TEST = "Testen",
        CRIT_SOUND = "Krit-Sound: %s",
        FINISHER_SOUND = "Finisher-Sound: %s",
        SHUFFLE = "Zufällig",
        DEBUG = "Diagnosemeldungen im Chat",
        DEBUG_HELP = "Die Diagnose zeigt erkannten Krit-Typ, Angriffszustand und verworfene Doppel-Ereignisse.",
        DETECTION = "Erkennung",
        DETECTION_HELP = "Die Krit-Zuordnung ist eine Schätzung: Gruppentreffer auf dasselbe Ziel können ebenfalls auslösen. Verborgene Kampfdaten werden übersprungen; Schaden kann fehlen.",
        CRIT_LABEL = "KRIT",
        FINISHER_LABEL = "TODESSTOSS",
        SPELL_CRIT = "Zauber-Krit erkannt",
        MELEE_CRIT = "Nahkampf-Krit erkannt",
        DUPLICATE = "Doppeltes UNIT_COMBAT-Ereignis verworfen",
        PARTY_RECEIVED = "Gruppen-BAM empfangen",
        CLAIM_DUPLICATE = "Krit bereits von einem Gruppenmitglied gemeldet, übersprungen",
        LOADED = "v%s geladen. /bam öffnet die Einstellungen.",
        ENABLED_MSG = "aktiviert",
        DISABLED_MSG = "deaktiviert",
        RESET_MSG = "Einstellungen zurückgesetzt.",
        SOUND_ERROR = "Sound konnte nicht abgespielt werden. Prüfe den sounds-Ordner.",
    },

    esES = {
        SETTINGS_TITLE = "Bam Together",
        SETTINGS_SUBTITLE = "Sonido BAM clásico para golpes críticos",
        ENABLED = "Activar Bam Together",
        MELEE_CRITS = "Activar con críticos cuerpo a cuerpo",
        SPELL_CRITS = "Activar con críticos de hechizos",
        FINISHER = "BAAAM! con un golpe crítico final/mortal",
        MUTE_IN_DUNGEON = "Silenciar el sonido y el chat de críticos en mazmorras",
        MUTE_IN_GROUP = "Silenciar el sonido y el chat de críticos en grupo",
        PARTY_BAM = "Compartir BAMs con el grupo y escuchar los suyos",
        CRIT_CHAT = "Mostrar el daño crítico en el chat",
        CHAT_EXAMPLE = "Ejemplo: BAM!  1.284 CRÍT  →  Objetivo",
        THROTTLE = "Intervalo anti-spam de sonidos: %.2f segundos",
        THROTTLE_HELP = "0 = cada crítico detectado. Este control solo afecta a los sonidos, no al chat.",
        TEST = "Probar",
        CRIT_SOUND = "Sonido de crítico: %s",
        FINISHER_SOUND = "Sonido de golpe final: %s",
        SHUFFLE = "Aleatorio",
        DEBUG = "Mensajes de diagnóstico en el chat",
        DEBUG_HELP = "El diagnóstico muestra el tipo de crítico, el estado del ataque y los eventos duplicados descartados.",
        DETECTION = "Detección",
        DETECTION_HELP = "La detección de críticos es aproximada: los golpes del grupo al mismo objetivo también pueden activarla. Los datos ocultos se omiten; el daño puede no estar disponible.",
        CRIT_LABEL = "CRÍT",
        FINISHER_LABEL = "GOLPE FINAL",
        SPELL_CRIT = "Crítico de hechizo detectado",
        MELEE_CRIT = "Crítico cuerpo a cuerpo detectado",
        DUPLICATE = "Evento UNIT_COMBAT duplicado descartado",
        PARTY_RECEIVED = "BAM de grupo recibido",
        CLAIM_DUPLICATE = "Crítico ya reclamado por un miembro del grupo, omitido",
        LOADED = "v%s cargado. /bam abre los ajustes.",
        ENABLED_MSG = "activado",
        DISABLED_MSG = "desactivado",
        RESET_MSG = "Ajustes restablecidos.",
        SOUND_ERROR = "No se pudo reproducir el sonido. Comprueba la carpeta sounds.",
    },

    frFR = {
        SETTINGS_TITLE = "Bam Together",
        SETTINGS_SUBTITLE = "Son BAM classique pour les coups critiques",
        ENABLED = "Activer Bam Together",
        MELEE_CRITS = "Déclencher sur les critiques en mêlée",
        SPELL_CRITS = "Déclencher sur les critiques de sorts",
        FINISHER = "BAAAM! lors d'un coup critique final/mortel",
        MUTE_IN_DUNGEON = "Couper le son et le chat des critiques dans les donjons",
        MUTE_IN_GROUP = "Couper le son et le chat des critiques en groupe",
        PARTY_BAM = "Partager les BAM avec le groupe et entendre les leurs",
        CRIT_CHAT = "Afficher les dégâts critiques dans le chat",
        CHAT_EXAMPLE = "Exemple : BAM!  1 284 CRIT  →  Cible",
        THROTTLE = "Délai anti-spam des sons : %.2f secondes",
        THROTTLE_HELP = "0 = chaque critique détecté. Ce réglage affecte uniquement les sons, pas le chat.",
        TEST = "Tester",
        CRIT_SOUND = "Son des critiques : %s",
        FINISHER_SOUND = "Son du coup final : %s",
        SHUFFLE = "Aléatoire",
        DEBUG = "Messages de diagnostic dans le chat",
        DEBUG_HELP = "Le diagnostic affiche le type de critique, l'état de l'attaque et les événements en double ignorés.",
        DETECTION = "Détection",
        DETECTION_HELP = "La détection des critiques est approximative : les coups du groupe sur la même cible peuvent aussi la déclencher. Les données masquées sont ignorées ; les dégâts peuvent manquer.",
        CRIT_LABEL = "CRIT",
        FINISHER_LABEL = "COUP FINAL",
        SPELL_CRIT = "Critique de sort détecté",
        MELEE_CRIT = "Critique de mêlée détecté",
        DUPLICATE = "Événement UNIT_COMBAT dupliqué ignoré",
        PARTY_RECEIVED = "BAM de groupe reçu",
        CLAIM_DUPLICATE = "Critique déjà signalé par un membre du groupe, ignoré",
        LOADED = "v%s chargé. /bam ouvre les paramètres.",
        ENABLED_MSG = "activé",
        DISABLED_MSG = "désactivé",
        RESET_MSG = "Paramètres réinitialisés.",
        SOUND_ERROR = "Impossible de lire le son. Vérifiez le dossier sounds.",
    },

    itIT = {
        SETTINGS_TITLE = "Bam Together",
        SETTINGS_SUBTITLE = "Classico suono BAM per i colpi critici",
        ENABLED = "Attiva Bam Together",
        MELEE_CRITS = "Attiva con i critici in mischia",
        SPELL_CRITS = "Attiva con i critici degli incantesimi",
        FINISHER = "BAAAM! con un colpo critico finale/mortale",
        MUTE_IN_DUNGEON = "Disattiva suono e chat dei critici nelle spedizioni",
        MUTE_IN_GROUP = "Disattiva suono e chat dei critici quando sei in gruppo",
        PARTY_BAM = "Condividi i BAM con il gruppo e ascolta i loro",
        CRIT_CHAT = "Mostra i danni critici in chat",
        CHAT_EXAMPLE = "Esempio: BAM!  1.284 CRIT  →  Bersaglio",
        THROTTLE = "Intervallo anti-spam dei suoni: %.2f secondi",
        THROTTLE_HELP = "0 = ogni critico rilevato. Questo cursore influenza solo i suoni, non la chat.",
        TEST = "Prova",
        CRIT_SOUND = "Suono dei critici: %s",
        FINISHER_SOUND = "Suono del colpo finale: %s",
        SHUFFLE = "Casuale",
        DEBUG = "Messaggi diagnostici in chat",
        DEBUG_HELP = "La diagnostica mostra il tipo di critico, lo stato dell'attacco e gli eventi duplicati ignorati.",
        DETECTION = "Rilevamento",
        DETECTION_HELP = "Il rilevamento dei critici è approssimativo: anche i colpi del gruppo sullo stesso bersaglio possono attivarlo. I dati nascosti vengono ignorati; i danni potrebbero non essere disponibili.",
        CRIT_LABEL = "CRIT",
        FINISHER_LABEL = "COLPO FINALE",
        SPELL_CRIT = "Critico da incantesimo rilevato",
        MELEE_CRIT = "Critico in mischia rilevato",
        DUPLICATE = "Evento UNIT_COMBAT duplicato ignorato",
        PARTY_RECEIVED = "BAM del gruppo ricevuto",
        CLAIM_DUPLICATE = "Critico già segnalato da un membro del gruppo, ignorato",
        LOADED = "v%s caricato. /bam apre le impostazioni.",
        ENABLED_MSG = "attivato",
        DISABLED_MSG = "disattivato",
        RESET_MSG = "Impostazioni ripristinate.",
        SOUND_ERROR = "Impossibile riprodurre il suono. Controlla la cartella sounds.",
    },
}

-- Latin-American Spanish currently shares the Spanish translation.
translations.esMX = translations.esES
-- English UK uses the same strings as English US.
translations.enGB = translations.enUS

local active = translations[locale] or translations.enUS
local fallback = translations.enUS

Bam.L = setmetatable({}, {
    __index = function(_, key)
        return active[key] or fallback[key] or key
    end,
})

Bam.locale = locale
